# Generated by Django 5.2.6 on 2025-09-30 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=100)),
                ('country_of_residence', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('passport_photo', models.ImageField(upload_to='passport_photos/')),
                ('passport_number', models.CharField(max_length=50)),
                ('passport_expiration', models.DateField()),
                ('visa_history', models.BooleanField()),
                ('travel_history', models.TextField()),
                ('motivation', models.TextField()),
                ('profession', models.CharField(max_length=200)),
                ('hobbies', models.TextField()),
                ('instagram', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('intro_video', models.FileField(upload_to='intro_videos/')),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
