# Generated by Django 5.2.6 on 2025-10-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_passport_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='travel_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='visa_history',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
