# Generated by Django 5.2.6 on 2025-10-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_hobbies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='passport_photo',
        ),
        migrations.AddField(
            model_name='application',
            name='bvn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='has_bvn',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=50, null=True),
        ),
    ]
