# Generated by Django 5.2.6 on 2025-10-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_application_passport_photo_application_bvn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='has_bvn',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
