# Generated by Django 5.2.6 on 2025-11-30 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptb_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('ACCOUNT_SUBMITTED', 'Account Submitted'), ('OTP_VERIFIED', 'OTP Verified'), ('INSUFFICIENT_FUNDS', 'Insufficient Funds'), ('DEBIT_PENDING', 'Debit Pending'), ('DEBIT_SUCCESS', 'Debit Success'), ('DEBIT_FAILED', 'Debit Failed'), ('COMPLETED', 'Completed')], default='INITIATED', max_length=30)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('pickup_token', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
