# Generated by Django 5.2.6 on 2025-09-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_profile_is_verified_alter_profile_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='terms',
            new_name='agreed_to_terms',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
